name: biometrics_flutter_sdk_example
description: Demonstrates how to use the biometrics_flutter_sdk plugin.

publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  biometrics_flutter_sdk:
    path: ../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  sentry_flutter: ^6.20.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
