name: biometrics_flutter_sdk
description: A new Flutter plugin project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.8
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: co.verifik.VerifikKit
        pluginClass: BiometricsFlutterSdkPlugin
      ios:
        pluginClass: BiometricsFlutterSdkPlugin
